### ISSUE TITLE
PDFs...

### ISSUE THREAD

**Issue by paleobiologyGrader** [nloveless/Paleobio#2]
Hey Nathan,

I know you said that you already re-uploaded everything not as a PDF, but everything is still showing as a PDF for me. Are you sure it worked?

**Comment by nloveless** [comment]
Ok, I'm not sure what went wrong the first time, but I just tried again and checked and it is all showing on GitHub now. Should be good. Let me know if there are any more problems.

**Comment by paleobiologyGrader** [comment]
Great job! Once you've fixed an issue, you should close it.
