### ISSUE TITLE
Reading 5

### ISSUE THREAD

**Issue by paleobiologyGrader** [nloveless/Paleobio#6]
Where is your number 5 reading?

**Comment by nloveless** [comment]
Shoot, I had tried to submit my week 5 materials. I wasn't in lab to do it because of a Physics test, but I tried to do it early on Monday and thought it worked. I will figure it out right now

**Comment by paleobiologyGrader** [comment]
No problem! See me during class if it's still not working.

**Comment by nloveless** [comment]
Ok, it's showing that it is on my GitHub now. Should be good.

**Comment by paleobiologyGrader** [comment]
Excellent, Finished grading.
